import "./apothecary.cy";
import "./bedroom.cy";
import "./checkpoints.cy";
import "./finalPuzzle.cy";
import "./growthPotion.cy";
import "./keywords.cy";
import "./shrinkPotion.cy";
import "./southHall.cy";
import "./tunnels.cy";
