/***********/
/* GoNorth */
/***********/

/**
 * Global gonorth configuration options.
 */
export interface Config {
  /** The game's title, as it will appear on the title screen. */
  title: string;
  /** The game's author, as it will appear on the title screen. */
  author?: string;
  /** The game's version, as it will appear on the title screen. */
  version?: string;
  /** When set to false, does not immediately display the title screen. */
  goToTitleScreen?: boolean;
  /** The function that initialises all of your game's objects. */
  initialiser?: Initialiser;
  /** The store name, as it will appear in the browser's local storage. */
  storeName?: string;
  /** When set to `true`, verbose logging will be printed to the console. */
  debugMode?: boolean;
  /** When set to true, gonorth does not enforce a minimum time between user inputs. */
  skipReactionTimes?: boolean;
  /** When set to true, renders components allowing players to provide feedback. */
  renderFeedbackBox?: boolean;
  /** When set to true, records detailed logs of player input, to be used with feedback. */
  recordLogs?: boolean;
  /** The name gonorth will use to refer to the player. */
  referToPlayerAs?: string;
  /**
   * Function to handle player feedback,
   * @param feedback The player's feedback text.
   * @param name The player's name.
   * @param logs The detailed logs of player input and gonorth output.
   */
  feedbackHandler?: (feedback: string, name: string, logs: LogEntry[]) => void;
  /**
   * If provided, the same pseudo-random sequence of numbers will be used each time, allowing for predictable outputs.
   * Otherwise, a random seed will be used.
   */
  randomSeed?: string;
  /** If set to true, game state will not be saved in local storage. */
  skipPersistence?: boolean;
  /** The image to use on the start screen. */
  startScreenImage?: string;
  /** If set to true, the game's title is not displayed on the start screen. Useful if e.g. the image contains the title. */
  hideTitle?: boolean;
  /** CSS selector used to find the element gonorth will attach to. Will use the first element if many are selected. */
  elementSelector?: string;
}

/**
 * Interface for a Game object generated by Gonorth.
 */
export interface Game {
  /** The game's title. */
  title: string;
  /** The game's author. */
  author?: string;
  /** The Config object Gonorth was initialised with. */
  config: Config;
  /** The HTML element Gonorth is attached to. */
  container?: Element;
  /** Actions to be performed as part of the game's intro. */
  introActions: ActionChainT;
  /** The OptionGraph that will be be triggered when the player types 'help'. */
  help: OptionGraphT;
  /** The OptionGraph that will be triggered when the player types 'hint' */
  hintGraph: OptionGraphT;
  /** The function that initialises all of your game's objects. */
  initialiser?: Initialiser;
  /** The React component containing Gonorth's UI elements. */
  component?: import("react").ReactElement;
  /** The game's version. */
  version?: string;
}

export type Initialiser = () => void;
export type Intro = string | string[] | AnyText;

/***********/
/* Classes */
/***********/

export type ItemT = import("../game/items/item").Item;
export type ItemBuilderT = import("../game/items/item").Builder;
export type RoomT = import("../game/items/room").Room;
export type TextT = import("../game/interactions/text").Text;
export type SequentialTextT = import("../game/interactions/text").SequentialText;
export type CyclicTextT = import("../game/interactions/text").CyclicText;
export type PagedTextT = import("../game/interactions/text").PagedText;
export type RandomTextT = import("../game/interactions/text").RandomText;
export type ConcatTextT = import("../game/interactions/text").ConcatText;
export type ManagedTextT = import("../game/interactions/text").ManagedText;
export type InteractionT = import("../game/interactions/interaction").Interaction;
export type EventT = import("../game/events/event").Event;
export type ScheduleT = import("../game/events/schedule").Schedule;
export type RouteT = import("../game/events/route").Route;
export type EffectsT = import("../utils/effects").Effects;
export type EffectT = import("../utils/effects").Effect;
export type EffectBuilderT = import("../utils/effects").EffectBuilder;
export type VerbRelation = import("../utils/effects").VerbRelation;
export type ActionChainT = import("../utils/actionChain").ActionChain;
export type ActionClassT = import("../utils/actionChain").ActionClass;
export type OptionGraphT = import("../game/interactions/optionGraph").OptionGraph;
export type VerbT = import("../game/verbs/verb").Verb;
export type VerbBuilderT = import("../game/verbs/verb").VerbBuilder;
export type AutoActionT = import("../game/input/autoAction").AutoAction;
export type OptionT = import("../game/interactions/option").Option;
export type SnaphotPersistorT = import("../redux/snapshotPersistor").SnapshotPersistor;
export type ContainerT = import("../game/items/container").Container;
export type DoorT = import("../game/items/door").Door;
export type KeyT = import("../game/items/door").Key;
export type NpcT = import("../game/items/npc").Npc;

/********/
/* Text */
/********/

export interface ManagedTextPhase {
  text: TextT;
  times: number;
}

export interface SerializedManagedTextPhase {
  text: SerializedText;
  times: number;
}

export interface SerializedText {
  type: string;
  texts: string[];
  phases?: SerializedManagedTextPhase[];
}

export type AnyText = TextT | ManagedTextT;
export type TextFunction = (...args: any[]) => string | AnyText | TextFunction;
export type TextPart = string | TextFunction | AnyText;
export type UnknownText = string | string[] | AnyText | TextFunction;
export type ResolvedText = string | AnyText;

/*************/
/* Functions */
/*************/

export type Consumer = (value?: unknown) => void;
export type SimpleAction = () => void;

/*************************/
/* Persistent Properties */
/*************************/

export type AlteredProperties = Set<string>;
export type PersistentVariable = string | number | boolean | Record<string, unknown> | PersistentVariable[];
export type Snapshot = Record<string, any>;
export type RevivedSnapshot = Record<string, any>;

export interface JsonDict {
  [propertyName: string]: unknown;
}

/*********/
/* Redux */
/*********/

export interface AllItemsDict {
  [key: string]: ItemT;
}

export interface Keywords {
  [name: string]: VerbT;
}

export interface RoomDict {
  [name: string]: RoomT;
}

export interface OptionGraphDict {
  [name: string]: OptionGraphT;
}

export interface SerializableOptionGraph {
  currentNode?: string;
}

export interface SerializableOptionGraphDict {
  [name: string]: SerializableOptionGraph;
}

export interface SerializableSchedule {
  stage: number;
  state: string;
  currentEvent: SerializableEvent;
}

export interface SerializableScheduleDict {
  [id: string]: SerializableSchedule;
}

export interface SerializableEvent {
  state: string;
  countdown?: number;
}

export interface SerializableEventDict {
  [id: string]: SerializableEvent;
}

export interface StoreState {
  turn: number;
  debugMode: boolean;
  player?: ItemT;
  interaction: InteractionT;
  reverseInteraction: InteractionT;
  image?: string;
  lastChange: number;
  verbNames: VerbNameDict;
  // The names of items (including aliases) the player has encountered.
  itemNames: Set<string>;
  actionChainPromise?: Promise<string>;
  events: EventT[];
  schedules: ScheduleT[];
  keywords: Keywords;
  room?: RoomT;
  recordChanges: false;
  rooms: RoomDict;
  allItemNames: Set<string>;
  items: ItemAliasDict; // Keyed by alias
  allItems: Set<ItemT>;
  optionGraphs: OptionGraphDict;
  customState: CustomState;
  startingRoom?: RoomT;
  cyCommands: string[];
  cySay?: string;
  cyChoose?: string;
  eventTimeoutOverride?: number;
  eventTurnsOverride?: number;
  effects: EffectsT;
  autoActions: AutoActionT[];
  rollingLog: LogEntry[];
  playerInput?: string;
  game?: Game;
  gameStarted: boolean;
  sceneRevealed: boolean;
  feedbackOpen: boolean;
  roomName?: string;
}

export interface Dict {
  [key: string]: unknown;
}

export interface KeywordsDict {
  [name: string]: VerbT;
}

export interface ItemAliasDict {
  [alias: string]: Set<ItemT>;
}

export interface CustomState {
  [key: string]: Serializable;
}

export interface LogEntry {
  input: string;
  output: string[];
}

export interface LogOptions {
  global?: boolean;
  element?: string;
}

export interface ReduxAction {
  type: string;
  payload: any;
  keywords: VerbT[];
  keyword: string;
  room: RoomT;
  item: ItemT;
  optionGraph: OptionGraphT;
  snapshot: RevivedSnapshot;
  player: ItemT;
  force: boolean;
  propertyName: string;
  value: Serializable;
  startingRoom: RoomT;
  cySay: string;
  cyChoose: string;
  eventTimeoutOverride: boolean;
  eventTurnsOverride: boolean;
  autoAction: AutoActionT;
  playerTurn: boolean;
  gameStarted: boolean;
  sceneRevealed: boolean;
  feedbackOpen: boolean;
  roomName: string;
}

export type GetState = () => StoreState;

/*********************/
/* SnapshotPersistor */
/*********************/

export interface SnapshotPersistorConfig {
  version: number;
  name?: string;
  whitelist: string[];
  serializers: {
    [field: string]: (...args: any[]) => Serializable;
  };
  deserializers: {
    [key: string]: (value: Serializable) => unknown;
  };
}

export interface SerializedItem {
  [property: string]: Serialized;
  name: string;
  isItem: boolean;
}

export interface SerializedText {
  isText: boolean;
  partial: boolean;
}

export interface SerializedItemsDict {
  [name: string]: SerializedItem;
}

export type Serializable = Serializable[] | string | Dict | boolean | number;
export type Serialized = Serializable | SerializedItem | SerializedItem[] | SerializedText | SerializedText[];

/***************/
/* ActionChain */
/***************/

export interface Context {
  [key: string]: unknown;
  verb: VerbT;
  item: ItemT;
  other?: ItemT;
  alias?: string;
}

export interface ActionChainHelpers {
  fail?: () => boolean;
  abort?: () => boolean;
}

export type ChainContext = Partial<Context> & ActionChainHelpers;
export type DefiniteContext = Context & ActionChainHelpers;
export type AnyContext = Context | ActionChainHelpers;

export interface EffectsDict {
  [primaryKey: string]: {
    [secondaryKey: string]: {
      [verbName: string]: EffectT;
    };
  };
}

export interface EffectConfig {
  primaryItem?: ItemOrString;
  secondaryItem: ItemOrString;
  verbName: string;
  successful: boolean;
  verbRelation: VerbRelation;
  tests: SmartTest[];
  actions: ContextAction[];
}

export type ActionFunction = (context: ChainContext) => MaybeAction;
export type ActionContextFunction = (context: DefiniteContext) => MaybeContextAction;
export type ActionBase =
  | ActionClassT
  | string
  | AnyText
  | InteractionT
  | ActionChainT
  | OptionGraphT
  | number
  | boolean
  | null
  | undefined
  | Promise<any>;
export type Action = ActionBase | Action[] | ActionFunction;
export type ContextAction = ActionBase | ContextAction[] | ActionContextFunction;
export type MaybeContextAction = ContextAction | undefined | void;
export type MaybeAction = Action | undefined | void;
export type MaybePromise = Promise<any> | undefined;
export type MaybeOptions = OptionT | OptionT[] | undefined;
export type MaybeChainContext = ChainContext | undefined;
export type ChainableFunction = (context?: ChainContext) => MaybePromise;
export type PostScript = TextT | (() => string) | string;
export type MaybePostScript = PostScript | undefined;
export type Resolve = (value?: unknown) => void;

/*********/
/* Verbs */
/*********/

export interface VerbDict {
  [name: string]: VerbT;
}

export interface VerbNameDict {
  [name: string]: string;
}

export interface VerbConfig {
  [property: string]: unknown;
  name: string;
  tests: (Test | SmartTest)[];
  onSuccess?: ContextAction | ContextAction[];
  onFailure?: ContextAction | ContextAction[];
  aliases?: string[];
  isKeyword?: boolean;
  prepositional?: boolean;
  interrogative?: string;
  prepositionOptional?: boolean;
  description?: string;
  expectedArgs?: string[];
}

export type TestFunction = (context: Context) => boolean;
export type Test = boolean | TestFunction;

// A verb test that includes its own failure response.
export interface SmartTest {
  test: TestFunction;
  onFailure: Action;
}

export interface DecisionTree {
  input: string;
  room: RoomT;
  tokens: string[];
  verbConstructions: {
    verbs: {
      [verbConstruction: string]: VerbConstruction;
    };
    notVerbs: {
      [verbConstruction: string]: VerbConstruction;
    };
  };
  registeredVerbs: string[];
  registeredItem?: string;
  registeredVerb?: string;
  actualVerb?: VerbT;
  verbSupported: boolean;
  roomItem?: ItemT;
  indirectItem?: ItemT;
  duplicateAliasItems?: ItemT[];
  duplicateAlias?: string;
  duplicateItemIsPrimary: boolean;
  tooManyDuplicates: boolean;
}

export interface VerbConstruction {
  numWords: number;
  verbIndex: number;
  possibleVerb: string;
  canonicalVerb?: string;
  endIndex?: number;
  keyword?: VerbT;
  roomVerb?: VerbT;
  itemDetails: ItemDetails[];
  roomItem?: ItemT;
  actualVerb?: VerbT;
  indirectItem?: ItemT;
  validCombination: boolean;
  itemConstructions: {
    [itemConstruction: string]: ItemConstruction;
  };
}

export interface ItemConstruction {
  numWords: number;
  itemIndex: number;
  endIndex: number;
  possibleItem: string;
  itemExists?: boolean;
  itemsWithName: ItemT[];
}

/**********/
/* Parser */
/**********/

export type DisambiguationCallback = (item: ItemT) => string | Promise<unknown>;

export interface ItemDetails {
  alias: string;
  itemsWithName: ItemT[];
  itemIndex: number;
}

/*****************/
/* Option Graphs */
/*****************/

export type Condition = () => boolean;
export type InventoryAction = (item: ItemT) => string;
export type SomeGraphOption = string | GraphOption | Action;

export interface GraphOption {
  id?: string;
  condition?: Condition;
  node?: string;
  skipNodeActions?: boolean;
  exit?: boolean;
  room?: RoomT;
  actions?: Action;
  inventoryAction?: InventoryAction;
}

export interface GraphOptions {
  [label: string]: SomeGraphOption;
}

export type UnknownOptions = GraphOptions | (() => GraphOptions);

export interface GraphNode {
  id: string;
  options?: UnknownOptions;
  visited?: boolean;
  actions?: Action;
  allowRepeats?: boolean;
  noEndTurn?: boolean;
  /** Don't record this node as the current node to be resumed at. */
  doNotResume?: boolean;
}

/********/
/* Misc */
/********/

export type ItemOrRoom = ItemT | RoomT;
export type ItemRoomOrString = ItemOrRoom | string;
export type ItemOrString = ItemT | string;
export type MaybeItemOrString = ItemOrString | undefined;
export type OptionAction = () => Promise<unknown>;

/********/
/* Item */
/********/

export interface VerbCustomisations {
  [verbName: string]: (verb: VerbT) => void;
}

export interface ItemConfig {
  [property: string]: unknown;
  name: string;
  description?: UnknownText;
  holdable?: boolean;
  size?: number;
  verbs?: VerbT | VerbBuilderT | (VerbT | VerbBuilderT)[];
  aliases?: string[];
  omitAliases?: string[];
  items?: (ItemT | ItemBuilderT)[];
  hidesItems?: (ItemT | ItemBuilderT)[];
  properties?: ItemProperties;
  verbCustomisations?: VerbCustomisations;
  producesSingular?: ItemT;
  plural?: boolean;
  notPersisted?: boolean;
}

export interface ItemItemsDict {
  [name: string]: ItemT[];
}

export interface ItemProperties {
  [key: string]: Serializable;
}

/********/
/* Room */
/********/

export interface RoomConfig {
  checkpoint?: boolean;
  verbs?: VerbT[];
  image?: string;
}

export interface DirectionObject {
  room?: RoomT | SimpleAction;
  test?: () => boolean;
  onSuccess?: ContextAction | ContextAction[];
  onFailure?: Action;
  directionName?: DirectionName;
  door?: DoorT;
}

export interface AdjacentRooms {
  [name: string]: DirectionObject;
}

export type DirectionName = string | "north" | "south" | "east" | "west" | "up" | "down";
export type Navigable = boolean | DoorT | (() => boolean);

/********/
/* Door */
/********/

export interface DoorConfig {
  [property: string]: unknown;
  name: string;
  description: UnknownText;
  open: boolean;
  locked: boolean;
  alwaysOpen?: boolean;
  transparent?: boolean;
  onLocked: Action;
  onNeedsKey: Action;
  onOpen: Action;
  onClose: Action;
  onUnlock: Action;
  aliases: string[];
  key: KeyT;
  traversals?: Traversal[];
  verbs?: VerbT[];
}

export interface TraversalConfig {
  aliases: string[];
  origin?: string;
  activationCondition?: Test;
  tests: SmartTest[];
  doorOpenTest?: SmartTest;
  onSuccess: Action[];
  onFailure: Action[];
  onPeekSuccess?: Action[];
  destination?: string;
}

export interface Traversal {
  aliases: string[];
  id: number;
  destination: string;
  activationCondition: TestFunction;
  tests: SmartTest[];
  doorOpenTest?: SmartTest;
  onSuccess: Action[];
  onFailure: Action[];
  onPeekSuccess: Action[];
}

/*************/
/* Container */
/*************/

export interface ContainerConfig {
  [property: string]: unknown;
  name: string;
  aliases: string[];
  closedDescription: UnknownText;
  openDescription: UnknownText;
  capacity: number;
  preposition: string;
  locked: boolean;
  open: boolean;
  holdable: boolean;
  size: number;
  closeable: boolean;
  transparent: boolean;
  verbs: VerbT[];
  lockable: boolean;
  key: string | KeyT;
  relinquishTests: SmartTest[];
  onOpen: Action;
  onClose: Action;
  onUnlock: Action;
  onLocked: Action;
  onAlreadyOpen: Action;
  onAlreadyClosed: Action;
  onAlreadyUnlocked: Action;
  onNeedsKey: Action;
  onWrongKey: Action;
}

/**************/
/* AutoAction */
/**************/

export type Input = (context: Context) => string;

/*********/
/* Event */
/*********/

export interface NumberFunctionContext {
  event: EventT;
}

export type NumberFunction = (contex: NumberFunctionContext) => number;
export type NumberResolve = NumberFunction | number;

/***************/
/* OptionGraph */
/***************/

export interface GraphContext {
  optionGraph: OptionGraphT;
}